import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1779055984396 implements MigrationInterface {
    name = 'Migration1779055984396'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "referral_steps" DROP CONSTRAINT "referral_steps_referralId_fkey"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" DROP CONSTRAINT "referral_steps_completedById_fkey"`);
        await queryRunner.query(`ALTER TABLE "referral_documents" DROP CONSTRAINT "referral_documents_referralId_fkey"`);
        await queryRunner.query(`ALTER TABLE "referral_documents" DROP CONSTRAINT "referral_documents_uploadedById_fkey"`);
        await queryRunner.query(`ALTER TABLE "referral_notes" DROP CONSTRAINT "referral_notes_referralId_fkey"`);
        await queryRunner.query(`ALTER TABLE "referral_notes" DROP CONSTRAINT "referral_notes_authorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" DROP CONSTRAINT "authorization_requests_referralId_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_referralId_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_actorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "referrals_patientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "referrals_referringProviderId_fkey"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "referrals_specialistId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_patients_fullName"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referral_steps_referralId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referral_docs_referralId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referral_notes_referralId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_auth_requests_referralId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_audit_logs_referralId_createdAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referrals_patientId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referrals_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referrals_specialtyType"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referrals_status_priority"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_referrals_createdAt"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" DROP CONSTRAINT "referral_steps_referralId_stepNumber_key"`);
        await queryRunner.query(`CREATE TABLE "insurance_plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payerId" character varying NOT NULL, "planName" character varying NOT NULL, "planType" character varying NOT NULL, "preAuthRequiredFor" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_126589a8cdea7f2a3e64caa3b37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."specialist_profiles_specialtytype_enum" AS ENUM('CARDIOLOGY', 'DERMATOLOGY', 'ORTHOPEDICS', 'NEUROLOGY', 'RADIOLOGY', 'GASTROENTEROLOGY', 'PULMONOLOGY', 'ENDOCRINOLOGY', 'ONCOLOGY', 'RHEUMATOLOGY')`);
        await queryRunner.query(`CREATE TABLE "specialist_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "specialtyType" "public"."specialist_profiles_specialtytype_enum" NOT NULL, "isAcceptingReferrals" boolean NOT NULL DEFAULT true, "zipCode" character varying, "spokenLanguages" text, "nextAvailableSlotDays" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_0c7669919f863cd0e218cf97ed" UNIQUE ("userId"), CONSTRAINT "PK_255dd7971fa30faa31b7971020a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "specialist_insurance_plans" ("specialistProfilesId" uuid NOT NULL, "insurancePlansId" uuid NOT NULL, CONSTRAINT "PK_7f15ed3391aa2a08bf59c3666a3" PRIMARY KEY ("specialistProfilesId", "insurancePlansId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f17aec253c1df0accb38b76d24" ON "specialist_insurance_plans" ("specialistProfilesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef636eafca02171cbd4cee28e0" ON "specialist_insurance_plans" ("insurancePlansId") `);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "insurancePlan"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "insurancePlanId" uuid`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "patients_mrn_key"`);
        await queryRunner.query(`ALTER TYPE "public"."step_status_enum" RENAME TO "step_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."referral_steps_status_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETE', 'SKIPPED')`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ALTER COLUMN "status" TYPE "public"."referral_steps_status_enum" USING "status"::"text"::"public"."referral_steps_status_enum"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."step_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" DROP COLUMN "completedAt"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ADD "completedAt" date`);
        await queryRunner.query(`ALTER TYPE "public"."auth_status_enum" RENAME TO "auth_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."authorization_requests_status_enum" AS ENUM('NOT_REQUIRED', 'PENDING', 'APPROVED', 'APPROVED_WITH_MODIFICATIONS', 'DENIED', 'APPEALING')`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ALTER COLUMN "status" TYPE "public"."authorization_requests_status_enum" USING "status"::"text"::"public"."authorization_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."auth_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" DROP COLUMN "submittedAt"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ADD "submittedAt" date`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" DROP COLUMN "resolvedAt"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ADD "resolvedAt" date`);
        await queryRunner.query(`ALTER TYPE "public"."referral_status_enum" RENAME TO "referral_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."referrals_status_enum" AS ENUM('INTAKE', 'CLINICAL_PREP', 'AUTHORIZATION', 'READY_TO_SUBMIT', 'SUBMITTED', 'SCHEDULING', 'CLOSED', 'CANCELLED', 'AUTH_DENIED')`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" TYPE "public"."referrals_status_enum" USING "status"::"text"::"public"."referrals_status_enum"`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" SET DEFAULT 'INTAKE'`);
        await queryRunner.query(`DROP TYPE "public"."referral_status_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."referral_priority_enum" RENAME TO "referral_priority_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."referrals_priority_enum" AS ENUM('ROUTINE', 'URGENT', 'STAT')`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "priority" TYPE "public"."referrals_priority_enum" USING "priority"::"text"::"public"."referrals_priority_enum"`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "priority" SET DEFAULT 'ROUTINE'`);
        await queryRunner.query(`DROP TYPE "public"."referral_priority_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."specialty_type_enum" RENAME TO "specialty_type_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."referrals_specialtytype_enum" AS ENUM('CARDIOLOGY', 'DERMATOLOGY', 'ORTHOPEDICS', 'NEUROLOGY', 'RADIOLOGY', 'GASTROENTEROLOGY', 'PULMONOLOGY', 'ENDOCRINOLOGY', 'ONCOLOGY', 'RHEUMATOLOGY')`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "specialtyType" TYPE "public"."referrals_specialtytype_enum" USING "specialtyType"::"text"::"public"."referrals_specialtytype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."specialty_type_enum_old"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP COLUMN "appointmentDate"`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD "appointmentDate" date`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP COLUMN "submittedAt"`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD "submittedAt" date`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP COLUMN "closedAt"`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD "closedAt" date`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum" RENAME TO "user_role_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('PHYSICIAN', 'NURSE_PRACTITIONER', 'ADMIN_STAFF', 'SPECIALIST', 'SUPER_ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum_old"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2fe90c44da84b034e30bdadb9d" ON "patients" ("mrn") `);
        await queryRunner.query(`CREATE INDEX "IDX_7eb2fe09652804a54576c0e494" ON "patients" ("fullName") `);
        await queryRunner.query(`CREATE INDEX "IDX_f13317f9bd1855cf28ba7f4820" ON "referral_steps" ("referralId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d09c5b0baf14c7cdb461edab73" ON "referral_steps" ("referralId", "stepNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_12ec902b7cd613a544e3d01733" ON "referral_documents" ("referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d26bab921316281a41f9d1348e" ON "referral_notes" ("referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_56dc0dad7797e6b92e1db9ce87" ON "authorization_requests" ("referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4cf2b5a0462c269312b42726f" ON "audit_logs" ("referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_11393ad94aa064557b1d774670" ON "audit_logs" ("referralId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a3687f43c0a90d68524034085" ON "referrals" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2ea4262719c2cb9378e9a697d" ON "referrals" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6d69e6e614c5afd44308f79e62" ON "referrals" ("specialtyType") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2c72a56af4adb37d59a92b032" ON "referrals" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_dba94b0e65d7e8ad9767065ba8" ON "referrals" ("status", "priority") `);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "FK_0f232d173fdcab18fc5af8cd46b" FOREIGN KEY ("insurancePlanId") REFERENCES "insurance_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ADD CONSTRAINT "FK_f13317f9bd1855cf28ba7f48209" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ADD CONSTRAINT "FK_54d70a641d376c6b0904778ff47" FOREIGN KEY ("completedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_documents" ADD CONSTRAINT "FK_12ec902b7cd613a544e3d01733f" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_documents" ADD CONSTRAINT "FK_c477eacc74ab95a798e6d00a338" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_notes" ADD CONSTRAINT "FK_d26bab921316281a41f9d1348e1" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_notes" ADD CONSTRAINT "FK_8f5da545122f0e2c6efce80c9ce" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ADD CONSTRAINT "FK_56dc0dad7797e6b92e1db9ce876" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_a4cf2b5a0462c269312b42726fe" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_2dc33f7f3c22e2e7badafca1d12" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_1a3687f43c0a90d685240340852" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_cf81416b3d13b0ed1a95fb67ff5" FOREIGN KEY ("referringProviderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "FK_9736c59593d20679f2368d27b77" FOREIGN KEY ("specialistId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "specialist_profiles" ADD CONSTRAINT "FK_0c7669919f863cd0e218cf97ede" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "specialist_insurance_plans" ADD CONSTRAINT "FK_f17aec253c1df0accb38b76d24a" FOREIGN KEY ("specialistProfilesId") REFERENCES "specialist_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "specialist_insurance_plans" ADD CONSTRAINT "FK_ef636eafca02171cbd4cee28e06" FOREIGN KEY ("insurancePlansId") REFERENCES "insurance_plans"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "specialist_insurance_plans" DROP CONSTRAINT "FK_ef636eafca02171cbd4cee28e06"`);
        await queryRunner.query(`ALTER TABLE "specialist_insurance_plans" DROP CONSTRAINT "FK_f17aec253c1df0accb38b76d24a"`);
        await queryRunner.query(`ALTER TABLE "specialist_profiles" DROP CONSTRAINT "FK_0c7669919f863cd0e218cf97ede"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_9736c59593d20679f2368d27b77"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_cf81416b3d13b0ed1a95fb67ff5"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP CONSTRAINT "FK_1a3687f43c0a90d685240340852"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_2dc33f7f3c22e2e7badafca1d12"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_a4cf2b5a0462c269312b42726fe"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" DROP CONSTRAINT "FK_56dc0dad7797e6b92e1db9ce876"`);
        await queryRunner.query(`ALTER TABLE "referral_notes" DROP CONSTRAINT "FK_8f5da545122f0e2c6efce80c9ce"`);
        await queryRunner.query(`ALTER TABLE "referral_notes" DROP CONSTRAINT "FK_d26bab921316281a41f9d1348e1"`);
        await queryRunner.query(`ALTER TABLE "referral_documents" DROP CONSTRAINT "FK_c477eacc74ab95a798e6d00a338"`);
        await queryRunner.query(`ALTER TABLE "referral_documents" DROP CONSTRAINT "FK_12ec902b7cd613a544e3d01733f"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" DROP CONSTRAINT "FK_54d70a641d376c6b0904778ff47"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" DROP CONSTRAINT "FK_f13317f9bd1855cf28ba7f48209"`);
        await queryRunner.query(`ALTER TABLE "patients" DROP CONSTRAINT "FK_0f232d173fdcab18fc5af8cd46b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dba94b0e65d7e8ad9767065ba8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2c72a56af4adb37d59a92b032"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d69e6e614c5afd44308f79e62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2ea4262719c2cb9378e9a697d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a3687f43c0a90d68524034085"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11393ad94aa064557b1d774670"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4cf2b5a0462c269312b42726f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56dc0dad7797e6b92e1db9ce87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d26bab921316281a41f9d1348e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_12ec902b7cd613a544e3d01733"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d09c5b0baf14c7cdb461edab73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f13317f9bd1855cf28ba7f4820"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7eb2fe09652804a54576c0e494"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fe90c44da84b034e30bdadb9d"`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum_old" AS ENUM('PHYSICIAN', 'NURSE_PRACTITIONER', 'ADMIN_STAFF', 'SPECIALIST', 'SUPER_ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_enum_old" USING "role"::"text"::"public"."user_role_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_enum_old" RENAME TO "user_role_enum"`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP COLUMN "closedAt"`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD "closedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP COLUMN "submittedAt"`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD "submittedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "referrals" DROP COLUMN "appointmentDate"`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD "appointmentDate" TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."specialty_type_enum_old" AS ENUM('CARDIOLOGY', 'DERMATOLOGY', 'ORTHOPEDICS', 'NEUROLOGY', 'RADIOLOGY', 'GASTROENTEROLOGY', 'PULMONOLOGY', 'ENDOCRINOLOGY', 'ONCOLOGY', 'RHEUMATOLOGY')`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "specialtyType" TYPE "public"."specialty_type_enum_old" USING "specialtyType"::"text"::"public"."specialty_type_enum_old"`);
        await queryRunner.query(`DROP TYPE "public"."referrals_specialtytype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."specialty_type_enum_old" RENAME TO "specialty_type_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."referral_priority_enum_old" AS ENUM('ROUTINE', 'URGENT', 'STAT')`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "priority" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "priority" TYPE "public"."referral_priority_enum_old" USING "priority"::"text"::"public"."referral_priority_enum_old"`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "priority" SET DEFAULT 'ROUTINE'`);
        await queryRunner.query(`DROP TYPE "public"."referrals_priority_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."referral_priority_enum_old" RENAME TO "referral_priority_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."referral_status_enum_old" AS ENUM('INTAKE', 'CLINICAL_PREP', 'AUTHORIZATION', 'READY_TO_SUBMIT', 'SUBMITTED', 'SCHEDULING', 'CLOSED', 'CANCELLED', 'AUTH_DENIED')`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" TYPE "public"."referral_status_enum_old" USING "status"::"text"::"public"."referral_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "referrals" ALTER COLUMN "status" SET DEFAULT 'INTAKE'`);
        await queryRunner.query(`DROP TYPE "public"."referrals_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."referral_status_enum_old" RENAME TO "referral_status_enum"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" DROP COLUMN "resolvedAt"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ADD "resolvedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" DROP COLUMN "submittedAt"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ADD "submittedAt" TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."auth_status_enum_old" AS ENUM('NOT_REQUIRED', 'PENDING', 'APPROVED', 'APPROVED_WITH_MODIFICATIONS', 'DENIED', 'APPEALING')`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ALTER COLUMN "status" TYPE "public"."auth_status_enum_old" USING "status"::"text"::"public"."auth_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."authorization_requests_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."auth_status_enum_old" RENAME TO "auth_status_enum"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" DROP COLUMN "completedAt"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ADD "completedAt" TIMESTAMP`);
        await queryRunner.query(`CREATE TYPE "public"."step_status_enum_old" AS ENUM('PENDING', 'IN_PROGRESS', 'COMPLETE', 'SKIPPED')`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ALTER COLUMN "status" TYPE "public"."step_status_enum_old" USING "status"::"text"::"public"."step_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."referral_steps_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."step_status_enum_old" RENAME TO "step_status_enum"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD CONSTRAINT "patients_mrn_key" UNIQUE ("mrn")`);
        await queryRunner.query(`ALTER TABLE "patients" DROP COLUMN "insurancePlanId"`);
        await queryRunner.query(`ALTER TABLE "patients" ADD "insurancePlan" character varying`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef636eafca02171cbd4cee28e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f17aec253c1df0accb38b76d24"`);
        await queryRunner.query(`DROP TABLE "specialist_insurance_plans"`);
        await queryRunner.query(`DROP TABLE "specialist_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."specialist_profiles_specialtytype_enum"`);
        await queryRunner.query(`DROP TABLE "insurance_plans"`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ADD CONSTRAINT "referral_steps_referralId_stepNumber_key" UNIQUE ("referralId", "stepNumber")`);
        await queryRunner.query(`CREATE INDEX "IDX_referrals_createdAt" ON "referrals" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_referrals_status_priority" ON "referrals" ("priority", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_referrals_specialtyType" ON "referrals" ("specialtyType") `);
        await queryRunner.query(`CREATE INDEX "IDX_referrals_status" ON "referrals" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_referrals_patientId" ON "referrals" ("patientId") `);
        await queryRunner.query(`CREATE INDEX "IDX_audit_logs_referralId_createdAt" ON "audit_logs" ("createdAt", "referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_auth_requests_referralId" ON "authorization_requests" ("referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_referral_notes_referralId" ON "referral_notes" ("referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_referral_docs_referralId" ON "referral_documents" ("referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_referral_steps_referralId" ON "referral_steps" ("referralId") `);
        await queryRunner.query(`CREATE INDEX "IDX_patients_fullName" ON "patients" ("fullName") `);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "referrals_specialistId_fkey" FOREIGN KEY ("specialistId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "referrals_referringProviderId_fkey" FOREIGN KEY ("referringProviderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referrals" ADD CONSTRAINT "referrals_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_referralId_fkey" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "authorization_requests" ADD CONSTRAINT "authorization_requests_referralId_fkey" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_notes" ADD CONSTRAINT "referral_notes_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_notes" ADD CONSTRAINT "referral_notes_referralId_fkey" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_documents" ADD CONSTRAINT "referral_documents_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_documents" ADD CONSTRAINT "referral_documents_referralId_fkey" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ADD CONSTRAINT "referral_steps_completedById_fkey" FOREIGN KEY ("completedById") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral_steps" ADD CONSTRAINT "referral_steps_referralId_fkey" FOREIGN KEY ("referralId") REFERENCES "referrals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
