apiVersion: v1
kind: Secret
metadata:
  name: referrals-secrets
  namespace: referrals
type: Opaque
stringData:
  POSTGRES_PASSWORD: "referrals_secret"
  MINIO_ACCESS_KEY: "referrals_minio"
  MINIO_SECRET_KEY: "referrals_secret"
  JWT_SECRET: "Change_me_in_production_min_32_chars"
