import { Injectable } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { Repository } from "typeorm";
import { SpecialistProfile } from "../users/entities/specialist-profile.entity";
import { SpecialtyType } from "@referrals/shared";
import { Patient } from "../patients/entities/patient.entity";

export interface MatchedSpecialist {
  specialistUserId: string;
  specialistProfileId: string;
  fullName: string;
  score: number;
  reasons: string[];
}

@Injectable()
export class SpecialistMatchingService {
  constructor(
    @InjectRepository(SpecialistProfile)
    private readonly profileRepo: Repository<SpecialistProfile>,
  ) {}

  /**
   * Returns the highest-scoring specialist for the given patient and specialty,
   * or null if no eligible specialist is found.
   *
   * Candidate requirements (hard filters applied in DB):
   *   - specialtyType matches
   *   - isAcceptingReferrals = true
   *   - linked user is active
   *
   * Scoring (soft, applied in JS after fetch):
   *   +40  patient's insurance plan is in the specialist's accepted plans
   *   +30  specialist zip matches patient zip exactly
   *   +10  specialist zip prefix (first 3 digits) matches patient zip
   *   +20  specialist speaks patient's preferred language
   *   +10  next available slot ≤ 7 days
   *   + 5  next available slot ≤ 30 days
   */
  async findBestMatch(
    patient: Patient,
    specialtyType: SpecialtyType,
  ): Promise<MatchedSpecialist | null> {
    // Fetch all eligible candidates with their relations
    // We load acceptedInsurancePlans eagerly so we can check in-network status
    // in JS without a second round-trip.
    const candidates = await this.profileRepo
      .createQueryBuilder("sp")
      .innerJoinAndSelect("sp.user", "u")
      // Join table columns as generated by the migration:
      // "specialistProfilesId" and "insurancePlansId"
      .leftJoinAndSelect("sp.acceptedInsurancePlans", "plan")
      .where("sp.specialtyType = :specialtyType", { specialtyType })
      .andWhere("sp.isAcceptingReferrals = true")
      .andWhere("u.isActive = true")
      .getMany();

    if (!candidates.length) return null;

    const scored = candidates
      .map((profile) => this.score(profile, patient))
      .filter((m) => m.score > 0) // discard zero-score candidates
      .sort((a, b) => b.score - a.score); // highest score first

    return scored[0] ?? null;
  }

  // Private scoring logic

  private score(
    profile: SpecialistProfile,
    patient: Patient,
  ): MatchedSpecialist {
    let score = 0;
    const reasons: string[] = [];

    // +40 — in-network insurance match
    // patient.insurancePlanId is the FK; compare against each accepted plan's id
    if (patient.insurancePlanId) {
      const inNetwork = profile.acceptedInsurancePlans?.some(
        (plan) => plan.id === patient.insurancePlanId,
      );
      if (inNetwork) {
        score += 40;
        reasons.push("In-network with patient insurance");
      }
    }

    // +30 / +10 — location proximity via zip code
    // so zip is just a plain VARCHAR — direct comparison is fine.
    if (profile.zipCode && patient.zip) {
      if (profile.zipCode === patient.zip) {
        score += 30;
        reasons.push("Same zip code as patient");
      } else if (profile.zipCode.slice(0, 3) === patient.zip.slice(0, 3)) {
        score += 10;
        reasons.push("Same zip-code prefix as patient");
      }
    }

    // +10 / +5 — appointment availability
    if (profile.nextAvailableSlotDays != null) {
      if (profile.nextAvailableSlotDays <= 7) {
        score += 10;
        reasons.push(
          `Available within ${profile.nextAvailableSlotDays} day(s)`,
        );
      } else if (profile.nextAvailableSlotDays <= 30) {
        score += 5;
        reasons.push(
          `Available within ${profile.nextAvailableSlotDays} day(s)`,
        );
      }
    }

    return {
      specialistUserId: profile.user.id,
      specialistProfileId: profile.id,
      fullName: profile.user.fullName,
      reasons,
      score,
    };
  }
}
