export enum AuthorizationStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  APPROVED_WITH_MODIFICATIONS = 'APPROVED_WITH_MODIFICATIONS',
  DENIED = 'DENIED',
  APPEALING = 'APPEALING',
}
