export enum ReferralStatus {
  INTAKE = 'INTAKE',
  CLINICAL_PREP = 'CLINICAL_PREP',
  AUTHORIZATION = 'AUTHORIZATION',
  READY_TO_SUBMIT = 'READY_TO_SUBMIT',
  SUBMITTED = 'SUBMITTED',
  SCHEDULING = 'SCHEDULING',
  CLOSED = 'CLOSED',
  CANCELLED = 'CANCELLED',
  AUTH_DENIED = 'AUTH_DENIED',
}
