export enum SpecialtyType {
  CARDIOLOGY = 'CARDIOLOGY',
  DERMATOLOGY = 'DERMATOLOGY',
  ORTHOPEDICS = 'ORTHOPEDICS',
  NEUROLOGY = 'NEUROLOGY',
  RADIOLOGY = 'RADIOLOGY',
  GASTROENTEROLOGY = 'GASTROENTEROLOGY',
  PULMONOLOGY = 'PULMONOLOGY',
  ENDOCRINOLOGY = 'ENDOCRINOLOGY',
  ONCOLOGY = 'ONCOLOGY',
  RHEUMATOLOGY = 'RHEUMATOLOGY',
}
